export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'


export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'


export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'


export const GET_USER_ORDERS_REQUEST = 'GET_USER_ORDERS_REQUEST'
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS'
export const GET_USER_ORDERS_FAIL = 'GET_USER_ORDERS_FAIL'

export const GET_ORDERS_SUMMARY_REQUEST = 'GET_ORDERS_SUMMARY_REQUEST'
export const GET_ORDERS_SUMMARY_SUCCESS = 'GET_ORDERS_SUMMARY_SUCCESS'
export const GET_ORDERS_SUMMARY_FAIL = 'GET_ORDERS_SUMMARY_FAIL'


export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL'


export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'




