 export const  USER_SIGN_REQUEST = 'USER_SIGN_REQUEST'
 export const  USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS'
 export const  USER_SIGN_FAIL = 'USER_SIGN_FAIL'

 export const  USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
 export const  USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
 export const  USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

 export const  USER_SIGNOUT = 'USER_SIGNOUT'


 export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
 export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
 export const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED'

